- name: Add scoring user
  import_tasks: add_linux_user_with_ssh.yml
  vars:
    username: "{{ scoring_user_username }}"
    shell: "{{ scoring_user_shell }}"
    password_hash: "{{ scoring_user_password_hash }}"
    ssh_key_dir: "{{ scoring_users_ssh_key_dir }}"
    users_file_dir: "{{ scoring_users_dir }}"
    users_file_postfix: "{{ scoring_users_file_postfix }}"