- name: Get metadata of /etc/shadow
  ansible.builtin.stat:
    path: /etc/shadow
  register: shadow_metadata

- name: Read /etc/shadow
  ansible.builtin.slurp:
    path: /etc/shadow
  register: shadow_content

- name: Convert content to a list of lines
  set_fact:
    shadow_lines: "{{ shadow_content['content'] | b64decode | split('\n') }}"

- name: Shuffle the lines
  set_fact:
    shuffled_lines: "{{ shadow_lines | shuffle }}"

- name: Write the shuffled lines back to /etc/shadow with original metadata
  ansible.builtin.copy:
    content: "{{ shuffled_lines | join('\n') + '\n' }}"
    dest: /etc/shadow
    owner: "{{ shadow_metadata.stat.uid }}"
    group: "{{ shadow_metadata.stat.gid }}"
    mode: "{{ shadow_metadata.stat.mode | string | regex_replace('^0+', '') }}"